### ISSUE TITLE
Cursor Will Not Lock

### ISSUE THREAD

**Issue by pokl1** [snakemodule/FPoSu#1]
When playing my cursor won't lock to the center, with letterbox I can see the cursor outside of the small window when playing, this issue does not occur in McOsu using the First Person mod.

I attempted to record the issue but you're unable to see the cursor
https://streamable.com/wuow2

Specs:
OS: Win 7 Ultimate 32bit
GPU: ATI FireGL V3400
CPU: Dual Pentium E2180 2GHz

**Comment by snakemodule** [comment]
Fposu has been merged with McOsu. Issue closed.
